---
title: STATS 205 (Stanford)
summary: " Introduction to Nonparametric Statistics."
author: "PJ"
date: '2019-01-02'
slug: stats205
categories: []
tags: []
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
weight: 1
---

# Description

[Course link.](https://explorecourses.stanford.edu/search?q=STATS+205%3a+Introduction+to+Nonparametric+Statistics&view=catalog&filter-coursestatus-Active=on&academicYear=20182019)

 

# Syllabus

##  Course Overview

This course covers nonparametric analogs of the one- and two-sample t-tests and analysis of variance; the sign test, median test, Wilcoxon's tests, and the Kruskal-Wallis and Friedman tests, tests of independence; nonparametric regression and nonparametric density estimation; modern nonparametric techniques; nonparametric confidence interval estimates.

## Expected outcomes

By the end of the course, the student should be able to 

- understand the assumptions underlying the nonparametric methods
- apply nonparametric methods to modern data analysis problems
- get hands-on experience in implementing methods and using existing R packages.

##  Course Information

- Term: Spring 2019
- Units: 3
- Time: Mon, Wed, Fri 1:30 PM - 2:20 PM
- Location: 
- LEC: 04/01/2019 - 06/05/2019 (10 Weeks - 30 hours)

## Prerequisites
- [STATS 60](https://explorecourses.stanford.edu/search?view=catalog&filter-coursestatus-Active=on&page=0&catalog=&academicYear=20182019&q=STATS+60%3A+Introduction+to+Statistical+Methods%3A+Precalculus+&collapse=) or [STATS 110](https://explorecourses.stanford.edu/search?view=catalog&filter-coursestatus-Active=on&page=0&catalog=&academicYear=20182019&q=STATS+110%3A+Statistical+Methods+in+Engineering+and+the+Physical+Sciences&collapse=) or [STATS 160](https://explorecourses.stanford.edu/search?view=catalog&filter-coursestatus-Active=on&page=0&catalog=&academicYear=20182019&q=STATS+160%3A+Introduction+to+Statistical+Methods%3A+Precalculus+&collapse=); Students should familiar with summary statistics, hypothesis testing, point estimation, interval estimation (confidence intervals), basics of statistical inference, and [R](https://cran.r-project.org/).


##  Texts
- Required:
    - **(HWC)** [Nonparametric Statistical Methods](https://searchworks.stanford.edu/view/10356739).
        - Authors: Myles Hollander, Douglas A. Wolfe, Eric Chicken
        - Edition: $3^{rd}$ Edition
        - Print ISBN:9780470387375 
        - Online ISBN:9781119196037

- Recommended: 
    - **(DH)**: Davison and Hinkley (1997). Boostrap Method and Their Application.
    <!-- - **(EH)**: Efron and Hastie (2016). Computer Age Statistical Inference: Algorithms, Evidence, and Data Science. -->
    - **(ET)**: Efron and Tibshirani (1994). [An Introduction to the Bootstrap](https://searchworks.stanford.edu/view/9980237).
    - **(KM)**: Kloke and McKean (2015). [Nonparametric Statistical Methods Using R](https://searchworks.stanford.edu/view/10718635).
    - **(L)**: Lehmann (2006). Nonparametrics: Statistical Methods Based on Ranks.
    - **(RHG)**: Ramsay, Hooker, Graves (2009). [Functional Data Analysis with R and MATLAB](https://searchworks.stanford.edu/view/9109922).
    - **(W)**: Wasserman (2006). [All of Nonparametric Statistics](https://searchworks.stanford.edu/view/6263491).
    

##  Other sources
- Recommended Readings: a reading list will be posted on Canvas.
    - **Re:BHLLSW2009**: Buja, Cook, Hofmann, Lawrence, Lee, Swayne, and Wickham (2009). Statistical Inference for Exploratory Data Analysis and Model Diagnostics.
    - **Re:D1983**: Diaconis (1983). Theories of Data Analysis: From Magical Thinking Through Classical Statistics.
    - **Re:DH1994**: Diaconis and Holmes (1994). Gray Codes for Randomization Procedures.
    - **Re:DH1995**: Diaconis and Holmes (1995). Discrete Probability and Algorithms: Three Examples of Monte-Carlo Markov Chains: At the Interface Between Statistical Computing, Computer Science, and Statistical Mechanics, pg. 43-56.
    - **Re:JWH2014**: Josse, Wager, and Husson (2014). Confidence Areas for Fixed-Effects PCA.
    
- Useful links
    - **Li:H1997**: Holmes (1997). [Lecture Notes on Computer Intensive Methods in Statistics](http://statweb.stanford.edu/~susan/courses/b494/node3.html#SECTION00390000000000000000).
    - **Li:H2004**: Holmes (2004). [Lecture Notes on Complete Enumeration](http://statweb.stanford.edu/~susan/courses/s208/node40.html).
    - **Li:C2016**: Seiler (2016). [Lecture Notes on Nonparametric Statistics](http://christofseiler.github.io/stats205/).
    - **Li:W2016**: Wasserman (2016). [Lecture Notes on Nonparametric Bayesian Methods](http://www.stat.cmu.edu/~larry/=sml/nonparbayes.pdf).
    
##  Software
- In this course, we will use R for computing and R Markdown for producing lecture slides, solutions for homework assignments. R Markdown/Latex is highly recommended to write the midterm project proposal report and final project report. Install the following software:
    - R (required): [https://www.r-project.org/](https://www.r-project.org/).
    - R Studio is highly recommended for syntax highlighting, package management, document generation, and more: [https://www.rstudio.com/](https://www.rstudio.com/).
        - The newest version of R Studio is highly recommended (v1.1.463).
    - Latex, which will enable you to create PDFs directly from the R Markdown in RStudio.
        - Mac users should download macTeX [http://www.tug.org/mactex/downloading.html](http://www.tug.org/mactex/downloading.html) from Safari (not Chrome).
        - Windows users should install MiKTeX [https://miktex.org/download](https://miktex.org/download).

##  Grading
The final letter grade for this course will be determined by each method of assessment weighted as follows:

- Class participation (5%)
- Weekly homework assignments (50%)
- Midterm project proposal (10%, due on 05/03/2019)
- Final project (35%, due on 06/05/2019)

#  Lecture Notes

## Course Schedule

```{r echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
schedule <- "
|Date     | Week  | Topic                      |Reading        |Notes     |
|---------|-------|----------------------------|---------------|----------|
| **04/01/2019**|Week 1 [Lecture 0](Lecture_0_overview_setup.pdf)  | Overview of current research in nonparametric and adequate initiation to R and R Markdown| [ASA Nonparametric statistics section news](https://community.amstat.org/nonparametricstatisticssection/news) gives an overview of some current research topics; install [R](https://www.r-project.org/); install [RStudio](https://www.rstudio.com/products/rstudio/); [TryR](http://tryr.codeschool.com/), [R Markdown webinar](https://www.rstudio.com/resources/videos/r-markdown-eight-ways/), [R Markdown](https://rmarkdown.rstudio.com/) provide adequate initiation to R and R Markdown.| |
|**04/03/2019**| Week 1| Logistics and Preliminaries | Syllabus, HWC: Chapter  1||
|**04/05/2019**| Week 1| The One-sample problem I (testing procedure) | HWC: Chapter 3.4-3.6, 3.8, 3.1-3.3, 3.7|**Homework 1 posted**|
|**04/08/2019**| Week 2| The One-sample problem II (estimator associated with the statistic, confidence interval, example) | HWC: Chapter 3.4-3.6, 3.8, 3.1-3.3, 3.7||
|**04/10/2019**| Week 2|Statistical functionals and Influence functions| Notes will be posted on W: Chapter 2, ET: Chapter 4, 5, 21.3||
|**04/12/2019**|Week 2| Jackknife and Bootstrap I  | HWC: Chapter 8.4 and notes will be posted based on W: Chapter 3, DH, ET: Chapter 6, 11|**Homework 2 Posted**, **Homework 1 Due**|
|**04/15/2019**| Week 3 | Bootstrap II |Notes will be posted based on ET: Chapter 23, Re:DH1994, Re:DH1995 ||
|**04/17/2019**| Week 3|Discrete data problems I  |HWC: Chapter 2||
|**04/19/2019**| Week 3| Discrete data problems II |HWC: Chapter 10|**Homework 3 Posted**, **Homework 2 Due**|
|**04/22/2019**| Week 4| Two-sample problem I | HWC: Chapter 4||
|**04/24/2019**| Week 4| Two-sample problem II| HWC: Chapter 5||
|**04/26/2019**| Week 4| Permutation Test I | |**Homework 4 Posted**, **Homework 3 Due**|
|**04/29/2019**| Week 5| Permutation Test II| | |
|**05/01/2019**| Week 5| Ranked-based linear regression| HWC: Chapter 9| 
|**05/03/2019**| Week 5| Smoothing I  |W: Chapter 4|**Midterm project proposal due** |
|**05/06/2019**| Week 6| Nonparametric regression I  |HWC: Chapter 9.7, 14, W: Chapter 5  | |
|**05/08/2019**| Week 6|Nonparametric regression II | HWC: Chapter 9.7, 14, W: Chapter 5 | |    
|**05/10/2019**| Week 6| Wavelets|HWC: Chapter 13, W: Chapter 9 | **Homework 5 Posted**, **Homework 4 Due**|
|**05/13/2019**| Week 7|ANOVA I| HWC: Chapter 6, 7|   |
|**05/15/2019**| Week 7|ANOVA II , multiple comparison|HWC: Chapter 6, 7 | | 
|**05/17/2019**| Week 7|Survival analysis I |HWC: Chapter 10 | **Homework 6 Posted**, **Homework 5 Due**| 
|**05/20/2019**| Week 8|Survival analysis II | HWC: Chapter 10| | 
|**05/22/2019**| Week 8|Ranked set sampling | HWC: Chapter 15| |
|**05/24/2019**| Week 8| Bayesian nonparametric I|HWC: Chapter 16, Li:W2016 |**Homework 7 Posted**, **Homework 6 Due** |
|**05/27/2019**| Week 9|**(Holiday, no classes)** | |Memorial Day |
|**05/29/2019**| Week 9|Bayesian nonparametric II | HWC: Chapter 16, Li:W2016 | | 
|**05/31/2019**| Week 9|Inference for data visualization | Re:BHLLSW2009, Re:D1983, Re:JWH2014|**Homework 7 Due** (no late submission allowed, End-Quarter Period starts) |
|**06/03/2019**| Week 10|Multivariate nonparamteric tests, Bootstrap III |ET: Chapter 12, 14| |
|**06/05/2019**| Week 10|Wrap-up  | | **Final project due**|
"
cat(schedule)
```





